### ISSUE TITLE
Insurance 

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#14] opened 2020-06-03 08:05 UTC
Regression on insurance.csv (in Data Folder)
Output is 'Charges'
Input is all the rest.
Current loss: 0,01
Issue : no predictions are shown.

**Comment by hansvana** [comment] 2020-08-19 07:01
Cannot reproduce at this point. Which might mean it got fixed in a previous build. @erikk-avans can you confirm it works now?

**Comment by erikk-avans** [comment] 2020-09-03 08:42
Prediction are now shown. Problem : charges shows same value for all predictions.  Strong feature importance are bmi and smoker. Changing them does not cause different charges.

**Comment by hansvana** [comment] 2020-09-09 09:14
@erikk-avans Still can not reproduce, works fine for me. Can you check the version number at the top is ALPHA 0.2.6 when you run the training?

**Comment by erikk-avans** [comment] 2020-09-09 11:11
fixed in 0.2.6. Checked.

**Closed** 2020-09-20 10:27 UTC
Labels: bug
