### ISSUE TITLE
Belgian Wages result is different than NNTrainer test result with same values

### ISSUE THREAD

**Issue by ManoFea** [hansvana/ML5_NN_Trainer#25] opened 2020-09-02 12:46 UTC
Im using Education : 1, Experience:31 as my input and outputing wages.

in NNTrainer I get 10.79, in my own test page I get 0.6101542115211487

![Screen Shot 2020-09-02 at 2 29 20 PM](https://user-images.githubusercontent.com/26695701/91982808-13d00d00-ed2b-11ea-9d7f-5d0b533aacb7.png)
![Screen Shot 2020-09-02 at 2 27 53 PM](https://user-images.githubusercontent.com/26695701/91982812-1468a380-ed2b-11ea-8366-d822471715ba.png)
![Screen Shot 2020-09-02 at 2 07 17 PM](https://user-images.githubusercontent.com/26695701/91982817-1599d080-ed2b-11ea-863f-cd66e233a34a.png)

**Comment by ManoFea** [comment] 2020-09-02 13:17
Previous error solved, model instead of models

Now I have an issue with the results from the test in NNTrainer and my patch, see attachment, screenshots in the folder. cheers!

[firstModel_Pulse.zip](https://github.com/hansvana/ML5_NN_Trainer/files/5162522/firstModel_Pulse.zip)

**Comment by hansvana** [comment] 2020-09-03 08:52
The second problem was caused by https://github.com/hansvana/ML5_NN_Trainer/issues/13

This issue is fixed in 0.2.6

**Closed by hansvana** 2020-09-03 08:52 UTC
Labels: bug
